declare module "lucide-react" {
  import type { FC, SVGProps } from "react"
  export type Icon = FC<SVGProps<SVGSVGElement>>
  export type LucideIcon = Icon
  export const Activity: Icon
  export const AlertCircle: Icon
  export const AlertTriangle: Icon
  export const ArrowDown: Icon
  export const ArrowLeft: Icon
  export const ArrowRight: Icon
  export const ArrowUpDown: Icon
  export const ArrowUpRight: Icon
  export const Atom: Icon
  export const Ban: Icon
  export const BarChart3: Icon
  export const Bell: Icon
  export const BookOpen: Icon
  export const Bot: Icon
  export const Building2: Icon
  export const Calendar: Icon
  export const CalendarCheck: Icon
  export const Camera: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const CheckCircle2: Icon
  export const ChevronDown: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ClipboardList: Icon
  export const Clock: Icon
  export const Code2: Icon
  export const Copy: Icon
  export const Database: Icon
export const Cpu: Icon
  export const CreditCard: Icon
  export const DollarSign: Icon
  export const Download: Icon
  export const Edit3: Icon
  export const ExternalLink: Icon
  export const Eye: Icon
  export const Filter: Icon
  export const EyeOff: Icon
  export const FileJson: Icon
  export const FileText: Icon
  export const Globe: Icon
  export const HeartPulse: Icon
  export const HelpCircle: Icon
  export const Home: Icon
  export const Inbox: Icon
  export const Info: Icon
  export const Key: Icon
  export const Laptop: Icon
  export const Layout: Icon
  export const LayoutDashboard: Icon
  export const Lightbulb: Icon
  export const Link2: Icon
export const LockKeyhole: Icon
  export const Loader2: Icon
  export const LogOut: Icon
  export const Mail: Icon
  export const Menu: Icon
  export const MessageCircle: Icon
  export const MessageSquare: Icon
  export const Minus: Icon
  export const Monitor: Icon
  export const Moon: Icon
  export const MoreVertical: Icon
  export const Palette: Icon
  export const Paperclip: Icon
  export const Phone: Icon
  export const PhoneCall: Icon
  export const Play: Icon
  export const Plus: Icon
  export const Quote: Icon
  export const RefreshCw: Icon
  export const Save: Icon
  export const Search: Icon
  export const Send: Icon
  export const Settings: Icon
  export const Shield: Icon
  export const ShieldCheck: Icon
  export const ShoppingCart: Icon
  export const Webhook: Icon
  export const Sliders: Icon
  export const Smartphone: Icon
  export const Sparkles: Icon
  export const Star: Icon
  export const Stethoscope: Icon
  export const Sun: Icon
  export const Trash2: Icon
  export const TrendingUp: Icon
  export const Unlink: Icon
  export const Archive: Icon
  export const Upload: Icon
  export const User: Icon
  export const UserPlus: Icon
  export const Users: Icon
  export const X: Icon
  export const XCircle: Icon
  export const Zap: Icon
}
