import { prisma } from "@/lib/db"
import { randomUUID } from "crypto"
import { logger } from "@/lib/logger"
import { AI } from "@/config/constants"
import { buildSystemPrompt } from "./prompt"
import { getOpenRouterConfig, type OpenRouterProviderError } from "./providers"
import { callOpenRouterWithFailover } from "./openrouter-manager"
import { generateFallbackResponse } from "./fallback"
import { searchKnowledge, formatRAGContext, type KnowledgeEntry } from "./rag"
import {
  validateInput,
  buildEmergencyResponse,
  buildMedicalQueryResponse,
} from "./guardrails"
import { CLINOT_REDIRECT } from "./clinot-domain"
import { trackAiUsage, estimateTokens } from "./usage"
import { buildToolDefinitions, executeToolCall, type ToolCall, type ToolResult } from "./tools"
import type { ChatMessage } from "@/types"

function buildConversationContext(
  userMessage: string,
  conversationHistory: ChatMessage[],
): ChatMessage[] {
  const history = conversationHistory.slice(-AI.maxHistoryMessages)

  const grouped: ChatMessage[] = []
  for (const msg of history) {
    const last = grouped[grouped.length - 1]
    if (last && last.role === msg.role) {
      last.content += "\n" + msg.content
    } else {
      grouped.push({ ...msg })
    }
  }

  const userMsg: ChatMessage = { role: "user", content: userMessage.slice(0, AI.maxUserMessageLength) }
  return [...grouped, userMsg]
}

/**
 * Machine-readable reason explaining why the final response was NOT
 * generated by OpenRouter. Undefined means OpenRouter produced the
 * response. Logged on every call so production can answer "why did
 * this message get a scripted response?" without any PII.
 */
/** Map a typed provider error to its machine-readable fallback reason. */
function fallbackReasonForProviderError(err: OpenRouterProviderError): FallbackReason {
  return err.reasonCode
}

function isProviderError(err: unknown): err is OpenRouterProviderError {
  return Boolean(err && typeof err === "object" && "reasonCode" in err)
}

/**
 * NON-TOOLS chat completion (used by the website chat route). Same
 * single provider: OpenRouter.
 */
export async function generateAIResponse(
  userMessage: string,
  clinicId: string,
  conversationHistory: ChatMessage[] = [],
): Promise<string> {
  const guardrail = validateInput(userMessage)

  if (guardrail.action === "invalid" || guardrail.action === "spam") {
    logger.info("Input rejected by guardrails", { action: guardrail.action, confidence: guardrail.confidence })
    return guardrail.message || "I'm here to help with clinic-related questions. Could you please ask something else?"
  }

  if (guardrail.action === "abuse") {
    logger.info("Abuse detected", { confidence: guardrail.confidence })
    return guardrail.message || "I'm here to help. Please feel free to ask about our services and appointments."
  }

  if (guardrail.action === "off_topic") {
    logger.info("Off-topic detected", { confidence: guardrail.confidence })
    return guardrail.message || CLINOT_REDIRECT
  }

  try {
    const [clinic, knowledgeBase, faqs] = await Promise.all([
      prisma.clinic.findUnique({ where: { id: clinicId } }),
      prisma.knowledgeBase.findMany({ where: { clinicId } }),
      prisma.fAQ.findMany({ where: { clinicId } }),
    ])

    const allEntries: KnowledgeEntry[] = [
      ...knowledgeBase.map((k) => ({
        id: k.id,
        question: k.question,
        answer: k.answer,
        category: k.category,
        type: "knowledgebase" as const,
      })),
      ...faqs.map((f) => ({
        id: f.id,
        question: f.question,
        answer: f.answer,
        category: f.category,
        type: "faq" as const,
      })),
    ]

    const ragResults = searchKnowledge(userMessage, allEntries, 5)
    const ragContext = formatRAGContext(ragResults)

    if (guardrail.action === "emergency") {
      logger.info("Emergency detected in user message", { clinicId })
      return buildEmergencyResponse(clinic?.emergencyPhone)
    }

    const isMedicalQuery =
      guardrail.action === "medical_query" ||
      /\b(diagnos(e|is)|prescribe|prescription|medication|dosage|dose|should i (take|use|try|get)|what (medicine|medication|tablet|drug)|is this normal|second opinion)\b/i.test(userMessage)

    if (isMedicalQuery && !/\b(appointment|book|schedule)\b/i.test(userMessage)) {
      return buildMedicalQueryResponse() + `\n\nWould you like to schedule an appointment with our doctor instead?`
    }

    const messages = buildConversationContext(userMessage, conversationHistory)

    const systemPrompt = buildSystemPrompt({
      clinicName: clinic?.name || "our clinic",
      ragContext,
      hours: clinic?.openingHours || "",
      address: clinic?.address || "",
      phone: clinic?.phone || "",
      emergencyPhone: clinic?.emergencyPhone || "",
      isMedicalQuery,
    })

    const fullMessages: ChatMessage[] = [{ role: "system", content: systemPrompt }, ...messages]
    const config = getOpenRouterConfig()

    try {
      const result = await callOpenRouterWithFailover(fullMessages)
      if (result.ok && result.content.trim()) {
        const promptTokens = estimateTokens(systemPrompt + messages.map((m) => m.content).join(""))
        const completionTokens = estimateTokens(result.content)

        trackAiUsage(clinicId, {
          promptTokens,
          completionTokens,
          totalTokens: promptTokens + completionTokens,
        }, "clinot").catch((err) => {
          logger.error("Failed to track AI usage", { error: err })
        })

        logger.info("AI response generated", { provider: "openrouter", clinicId, model: result.model })
        return result.content
      }
      logger.warn("OpenRouter failover exhausted without a usable response", {
        clinicId,
        reason: result.ok ? "OPENROUTER_EMPTY_RESPONSE" : result.reason,
      })
    } catch (providerError: unknown) {
      if (isProviderError(providerError)) {
        logger.error("OpenRouter request failed", {
          provider: "openrouter",
          reason: providerError.reasonCode,
          error: providerError.message.slice(0, 200),
        })
      } else {
        logger.error("AI response error", { error: (providerError as Error)?.message })
      }
    }

    // Intentional, context-aware fallback (RAG-informed). Never a
    // silent provider failure mask — the failure was logged above.
    return await generateFallbackResponse({
      userMessage,
      clinicId,
      ragResults: { entries: allEntries, topK: 3 },
    })
  } catch (error: unknown) {
    const err = error as Error
    logger.error("AI response error", { error: err?.message })
    return await generateFallbackResponse({
      userMessage,
      clinicId,
    })
  }
}

export interface GenerateAIOptions {
  /**
   * Pre-built message list (e.g. the receptionist's short-term
   * context: [context header, ...recent turns, current user
   * message]). When provided, it is used verbatim and
   * `conversationHistory` is ignored. Guardrails, RAG and token
   * tracking still run on `userMessage`.
   */
  prebuiltMessages?: ChatMessage[]
  /**
   * Whether to include the appointment tool definitions in the
   * OpenRouter request. Tools are ONLY needed for the deterministic
   * booking-completion handoff; normal conversation omits them so
   * free/routed models cannot fail on tool schemas.
   */
  includeTools?: boolean
}

/**
 * Machine-readable reason explaining why the final response was NOT
 * generated by OpenRouter. Undefined means OpenRouter produced the
 * response.
 */
export type FallbackReason =
  | "GUARDRAIL_BLOCKED"
  | "OPENROUTER_NOT_CONFIGURED"
  | "OPENROUTER_AUTH_FAILED"
  | "OPENROUTER_RATE_LIMITED"
  | "OPENROUTER_TIMEOUT"
  | "OPENROUTER_NETWORK_ERROR"
  | "OPENROUTER_PROVIDER_ERROR"
  | "OPENROUTER_BAD_REQUEST"
  | "OPENROUTER_EMPTY_RESPONSE"
  | "OPENROUTER_INVALID_RESPONSE"
  | "ALL_OPENROUTER_MODELS_FAILED"
  | "AI_INTERNAL_ERROR"

/**
 * Canonical AI entry point for the WhatsApp receptionist.
 *
 * ONE PROVIDER: OpenRouter, via the env-configured failover manager
 * (openrouter-manager.ts). OPENROUTER_MODEL is the primary (always
 * first); OPENROUTER_FALLBACK_MODELS is the optional comma-separated
 * fallback chain. No provider chains, no fallback providers, no
 * hardcoded models. On failure: explicit trace + context-aware fallback.
 */
export async function generateAIResponseWithTools(
  userMessage: string,
  clinicId: string,
  conversationHistory: ChatMessage[] = [],
  maxTokens?: number,
  options?: GenerateAIOptions,
): Promise<{ response: string; toolCalls?: any[]; fallbackReason?: FallbackReason }> {
  const traceId = randomUUID().slice(0, 8)
  const trace = (fields: Record<string, unknown>) =>
    logger.info(`[CLINOT_AI_TRACE ${traceId}]`, fields)

  const guardrail = validateInput(userMessage)
  trace({
    stage: "guardrail",
    action: guardrail.action,
    confidence: guardrail.confidence,
  })

  if (guardrail.action === "invalid" || guardrail.action === "spam") {
    trace({ stage: "final", aiCallAttempted: false, fallbackReason: "GUARDRAIL_BLOCKED" })
    return { response: guardrail.message || "I'm here to help with clinic-related questions. Could you please ask something else?", toolCalls: [], fallbackReason: "GUARDRAIL_BLOCKED" }
  }

  if (guardrail.action === "abuse") {
    trace({ stage: "final", aiCallAttempted: false, fallbackReason: "GUARDRAIL_BLOCKED" })
    return { response: guardrail.message || "I'm here to help. Please feel free to ask about our services and appointments.", toolCalls: [], fallbackReason: "GUARDRAIL_BLOCKED" }
  }

  if (guardrail.action === "off_topic") {
    trace({ stage: "final", aiCallAttempted: false, fallbackReason: "GUARDRAIL_BLOCKED", deterministicPath: "OFF_TOPIC" })
    return { response: guardrail.message || CLINOT_REDIRECT, toolCalls: [], fallbackReason: "GUARDRAIL_BLOCKED" }
  }

  try {
    const [clinic, knowledgeBase, faqs] = await Promise.all([
      prisma.clinic.findUnique({ where: { id: clinicId } }),
      prisma.knowledgeBase.findMany({ where: { clinicId } }),
      prisma.fAQ.findMany({ where: { clinicId } }),
    ])

    const allEntries: KnowledgeEntry[] = [
      ...knowledgeBase.map((k) => ({
        id: k.id,
        question: k.question,
        answer: k.answer,
        category: k.category,
        type: "knowledgebase" as const,
      })),
      ...faqs.map((f) => ({
        id: f.id,
        question: f.question,
        answer: f.answer,
        category: f.category,
        type: "faq" as const,
      })),
    ]

    const ragResults = searchKnowledge(userMessage, allEntries, 5)
    const ragContext = formatRAGContext(ragResults)

    if (guardrail.action === "emergency") {
      logger.info("Emergency detected in user message", { clinicId })
      trace({ stage: "final", aiCallAttempted: false, deterministicPath: "EMERGENCY" })
      return { response: buildEmergencyResponse(clinic?.emergencyPhone), toolCalls: [] }
    }

    const isMedicalQuery =
      guardrail.action === "medical_query" ||
      /\b(diagnos(e|is)|prescribe|prescription|medication|dosage|dose|should i (take|use|try|get)|what (medicine|medication|tablet|drug)|is this normal|second opinion)\b/i.test(userMessage)

    if (isMedicalQuery && !/\b(appointment|book|schedule)\b/i.test(userMessage)) {
      trace({ stage: "final", aiCallAttempted: false, deterministicPath: "MEDICAL_QUERY" })
      return { response: buildMedicalQueryResponse() + `\n\nWould you like to schedule an appointment with our doctor instead?`, toolCalls: [] }
    }

    // Short-term context: when the caller provides a pre-built,
    // already-trimmed message list (receptionist's small context
    // window + topic header), use it verbatim. Otherwise fall back
    // to the standard rolling-window builder.
    const messages = options?.prebuiltMessages ??
      buildConversationContext(userMessage, conversationHistory)

    const systemPrompt = buildSystemPrompt({
      clinicName: clinic?.name || "our clinic",
      ragContext,
      hours: clinic?.openingHours || "",
      address: clinic?.address || "",
      phone: clinic?.phone || "",
      emergencyPhone: clinic?.emergencyPhone || "",
      isMedicalQuery,
    })

    const fullMessages: ChatMessage[] = [{ role: "system", content: systemPrompt }, ...messages]

    // ONE provider: OpenRouter free-model failover manager.
    const config = getOpenRouterConfig()
    // Secure by default: LLM tool use (which can write appointments)
    // must be explicitly opted into per call site. The WhatsApp
    // receptionist always passes includeTools: false and books only
    // through the deterministic confirmation gate.
    const includeTools = options?.includeTools === true
    const toolDefinitions = includeTools ? buildToolDefinitions() : []

    trace({
      stage: "provider_selected",
      aiCallAttempted: true,
      provider: "openrouter",
      failover: true,
      apiKeyPresent: Boolean(config.apiKey),
      source: "clinot",
      toolsIncluded: includeTools,
      contextMessageCount: fullMessages.length,
      ragUsed: ragContext.length > 0,
    })

    let response: string | null = null
    let toolCalls: any[] = []
    let chatMessages = fullMessages
    let failoverReason: FallbackReason | undefined

    // Tool-calling loop: needed only when tools are included (the
    // booking-completion handoff). Each iteration goes through the
    // OpenRouter failover manager; each tool result is fed back to
    // the model; text responses end the loop.
    for (let iteration = 0; iteration < 3; iteration++) {
      const failover = await callOpenRouterWithFailover(
        chatMessages,
        {
          tools: includeTools ? { tools: toolDefinitions } : undefined,
          traceId,
        },
      )
      if (!failover.ok) {
        failoverReason = failover.reason as FallbackReason
        trace({
          stage: "provider_error",
          aiCallAttempted: true,
          provider: "openrouter",
          providerSuccess: false,
          fallbackReason: failoverReason,
        })
        break
      }
      const providerResponse = { content: failover.content, toolCalls: failover.toolCalls }

      if (providerResponse.toolCalls.length > 0) {
        toolCalls.push(...providerResponse.toolCalls)

        const toolResults = await Promise.all(
          providerResponse.toolCalls.map(async (tc) => {
            logger.info("[AI-TOOL] Tool call requested", {
              clinicId,
              toolName: tc.function.name,
              arguments: tc.function.arguments,
            })

            // PRE-VALIDATION: Intercept book_appointment calls with missing required params
            if (tc.function.name === "book_appointment") {
              try {
                const args = JSON.parse(tc.function.arguments)
                const requiredFields = ["providerId", "startTime", "endTime", "reason", "patientName", "phone"]
                const missing = requiredFields.filter(f => !args[f] || (typeof args[f] === "string" && args[f].trim() === ""))
                if (missing.length > 0) {
                  logger.warn("[AI-TOOL] Pre-validation failed for book_appointment", { missing, clinicId })
                  return {
                    name: tc.function.name,
                    result: null,
                    error: `Missing required fields: ${missing.join(", ")}. Please collect all required information before booking.`
                  }
                }
              } catch {
                // If parsing fails, let the tool handle it
              }
            }

            const result = await executeToolCall({ name: tc.function.name, arguments: tc.function.arguments }, clinicId)
            logger.info("[AI-TOOL] Tool execution result", {
              clinicId,
              toolName: result.name,
              success: !result.error,
              error: result.error,
            })
            return { name: result.name, result: result.result, error: result.error }
          })
        )

        // If a booking succeeded but we have no text yet, record the
        // confirmation so the patient always gets a booking reply.
        const bookingResult = toolResults.find(r => r.name === "book_appointment" && r.result?.success)
        if (bookingResult?.result?.confirmation && (!response || !response.trim())) {
          response = bookingResult.result.confirmation
        }

        for (let i = 0; i < providerResponse.toolCalls.length; i++) {
          const tc = providerResponse.toolCalls[i]
          const result = toolResults[i]
          chatMessages.push({
            role: "assistant",
            content: null,
            tool_calls: [{
              id: tc.id,
              type: "function",
              function: { name: tc.function.name, arguments: tc.function.arguments }
            }]
          })
          const toolContent = result.error
            ? `Error: ${result.error}`
            : JSON.stringify(result.result)
          chatMessages.push({
            role: "tool",
            tool_call_id: tc.id,
            content: toolContent,
          })
        }
        continue
      }

      response = providerResponse.content
      break
    }

    if (!response || !response.trim()) {
      const emptyReason: FallbackReason = failoverReason ?? "OPENROUTER_EMPTY_RESPONSE"
      logger.warn("OpenRouter failover returned no usable content after tool loop", { clinicId, reason: emptyReason })
      trace({ stage: "final", aiCallAttempted: true, provider: "openrouter", providerSuccess: false, aiResponsePresent: false, fallbackReason: emptyReason })
      const emptyFallback = await generateFallbackResponse({ userMessage, clinicId })
      return {
        response: emptyFallback?.trim() || "I'm here to help with appointments and clinic questions. Could you please provide more details?",
        toolCalls,
        fallbackReason: emptyReason,
      }
    } else {
      const promptTokens = estimateTokens(systemPrompt + chatMessages.map((m) => m.content ?? "").join(""))
      const completionTokens = estimateTokens(response)

      trackAiUsage(clinicId, {
        promptTokens,
        completionTokens,
        totalTokens: promptTokens + completionTokens,
      }, "clinot").catch((err) => {
        logger.error("Failed to track AI usage", { error: err })
      })

      logger.info("AI response generated", { provider: "openrouter", clinicId, toolCalls: toolCalls.length })
      trace({ stage: "final", aiCallAttempted: true, provider: "openrouter", providerSuccess: true, aiResponsePresent: true, aiResponseLength: response.length, fallbackUsed: false })
      return { response, toolCalls }
    }
  } catch (error: unknown) {
    const err = error as Error

    // Typed provider errors map to explicit OPENROUTER_* reasons —
    // never swallowed, never mislabeled.
    if (isProviderError(error)) {
      const reason = fallbackReasonForProviderError(error)
      logger.error("OpenRouter request failed — falling back", {
        provider: "openrouter",
        reason,
        error: err?.message?.slice(0, 200),
      })
      trace({ stage: "final", aiCallAttempted: true, provider: "openrouter", providerSuccess: false, providerError: err?.message?.slice(0, 200), fallbackReason: reason })
      const fatalFallback = await generateFallbackResponse({ userMessage, clinicId })
      return {
        response: fatalFallback?.trim() || "I'm here to help with appointments and clinic questions. Could you please provide more details?",
        toolCalls: [],
        fallbackReason: reason,
      }
    }

    logger.error("AI response error", { error: err?.message })
    trace({ stage: "final", aiCallAttempted: false, aiInternalError: err?.message?.slice(0, 120), fallbackReason: "AI_INTERNAL_ERROR" })

    const errorFallback = await generateFallbackResponse({
      userMessage,
      clinicId,
    })
    let finalResponse = errorFallback
    if (!finalResponse || !finalResponse.trim()) {
      finalResponse = "I'm here to help with appointments and clinic questions. Could you please provide more details?"
    }

    // FINAL SAFETY NET: Ensure we NEVER return empty response for appointment-related queries
    const isAppointmentQuery = /\b(appointment|book|schedule|reschedule|cancel|visit|see\s*(a\s*)?doctor|checkup|cleaning|consult)\b/i.test(userMessage)
    if (isAppointmentQuery && (!finalResponse || !finalResponse.trim())) {
      logger.warn("Final safety net triggered for appointment query", { clinicId, userMessage })
      finalResponse = "I'd be happy to help you book an appointment! Please share your full name, phone number, reason for your visit, and your preferred date and time."
    }

    return { response: finalResponse, toolCalls: [], fallbackReason: "AI_INTERNAL_ERROR" }
  }
}
